openapi: 3.0.0
info:
  version: 0.0.1
  title: Vert.x Native Functions API
  license:
    name: Mozilla Public License (v2)
servers:
- url: http://github.com/ksclarke/vertx-native-functions
components:
  parameters:
    AccessTokenOrigin:
      name: origin
      in: query
      description: The origin of the page, consisting of a protocol, hostname and, optionally, port number
      schema:
        type: string
        format: uri
        example: https://client.example.com/
      required: false
    AccessTokenMessageId:
      name: messageId
      in: query
      description: A string that both prompts the server to respond with a web page instead of JSON, and allows the client to match access token service requests with the messages received
      schema:
        type: string
        example: 1234
      required: false
  responses:
    AccessTokenBrowserClient:
      description: The access token response for browser-based clients; note that this may represent an error condition
      content:
        application/json:
          schema:
            type: object
            properties:
              accessToken:
                type: string
              expiresIn:
                type: integer
        text/html:
          schema:
            type: string
            example: '<html><body><script>window.parent.postMessage({"messageId":"1234","accessToken":"TOKEN_HERE","expiresIn": 3600},"https://client.example.com/");</script></body></html>'
    AccessTokenNonBrowserMissingCredentials:
      description: The request is missing a required cookie
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                enum: [ missingCredentials ]
                example: missingCredentials
    AccessTokenNonBrowserInvalidCredentials:
      description: The request contains an invalid cookie
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                enum: [ invalidCredentials ]
                example: invalidCredentials
    InternalServerError:
      description: There was an internal server error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error
  securitySchemes:
    Admin:
      type: apiKey
      in: header
      name: X-API-KEY
paths:
  /2015-03-31/functions/function/invocations:
    post:
      summary: Function invocation
      description: Invokes a Vert.x Native Function
      operationId: invokeFunction
      requestBody:
        content:
          application/json:
            example: [ { "uid": "ark:/21198/00000000", "accessMode": 0 }, { "uid": "ark:/21198/11111111", "accessMode": 1 } ]
      responses:
        '201':
          description: The items have been successfully added
        '400':
          description: The request didn't contain valid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ INVALID_JSONARRAY, MALFORMED_INPUT_DATA ]
                    example: MALFORMED_INPUT_DATA
                  message:
                    type: string
        '401':
          description: API key is missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ INVALID_ADMIN_CREDENTIALS ]
                    example: INVALID_ADMIN_CREDENTIALS
                  message:
                    type: string
        '500':
          description: There was an internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: [ INTERNAL_ERROR ]
                    example: INTERNAL_ERROR
                  message:
                    type: string
