openapi: "3.0.3"
info:
  version: ${project.version}
  title: ${project.name}
  license:
    name: ${api.license.name}
    url: ${api.license.url}
servers:
  - url: ${openfaas.url}
paths:
  /:
    get:
      summary: Gets the HelloWorld function's response
      operationId: info.freelibrary.vertx.functions.HelloWorld
      responses:
        200:
          description: A Hello World response
          content:
            text/html:
              schema:
                type: string
                example: "<html><body><h3>Hello World!</h3></body></html>"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /echo:
    post:
      summary: Gets the Echo function's response to a POST request
      operationId: info.freelibrary.vertx.functions.Echo
      responses:
        200:
          description: A JSON response that echoes the request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EchoData"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    EchoData:
      type: object
      required:
        - method
        - path
        - absoluteURI
        - remoteAddress
        - headers
      properties:
        method:
          type: string
        path:
          type: string
        absoluteURI:
          type: string
        remoteAddress:
          type: string
        headers:
          type: object
        params:
          type: object
        cookies:
          type: array
          items: {
            type: object
          }
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: There was an internal server error
